var IndexCtrl = function($scope){
	$scope.examples = [
    { name: '基本的雙向綁定：ng-mode', href: 'hello.html' },
    { name: '資料初始化的 Directives：ng-init, ng-checked, ng-disabled 及 ng-readonly', href: 'init-ect.html' },
    { name: '進行 MVC 雙向綁定：ng-controller', href: 'controller.html' },
    { name: '有條件顯示或隱藏內容：ng-show 與 ng-hide', href: 'show-and-hide.html' },
    { name: '顯示陣列的內容：ng-repeat (一)', href: 'repeat-1.html' },
    { name: '顯示陣列的內容：ng-repeat (二)', href: 'repeat-2.html' },
    { name: '顯示陣列的內容：ng-repeat (三)', href: 'repeat-3.html' },
    { name: '點擊的事件綁定：ng-click 與 ng-dblclick（一）', href: 'click-dblclick-1.html' },
    { name: '點擊的事件綁定：ng-click 與 ng-dblclick（二）', href: 'click-dblclick-2.html' },
    { name: 'Filters（一）', href: 'filters-1.html' },
    { name: 'Filters（二）', href: 'filters-2.html' },
    { name: 'Filters（三）', href: 'filters-3.html' },
    { name: '顯示下拉選單：ng-options（一）', href: 'options-1.html' },
    { name: '顯示下拉選單：ng-options（二）', href: 'options-2.html' },
    { name: '顯示下拉選單：ng-options（三）', href: 'options-3.html' },
    { name: 'ng-change', href: 'change.html' },
    { name: 'ng-href 與 ng-src', href: 'href-src.html' },
    { name: 'Module', href: 'module.html' },
    { name: 'Dependency Injection', href: 'inject.html' },
    { name: 'Route 與 ng-view', href: 'route.html' },
    { name: 'ng-if', href: 'ngif.html' },
    { name: 'ngCalss', href: 'ngcalss.html' },
    { name: 'ng-class-even 與 ng-class-odd', href: 'ngclass-even-odd.html' },
    { name: 'ng-style', href: 'style.html' },
    { name: 'ng-list', href: 'list.html' },
    { name: 'ng-focus 與 ngBlur', href: 'focus-blur.html' },
    { name: '自訂過濾器', href: 'custom-filter.html' },
    { name: '自訂表達式（模板）符號', href: 'custom-interpolation.html' },
    { name: 'ng-bind', href: 'bind.html' },
    { name: 'ng-submit', href: 'submit.html' },
    { name: 'Todos', href: 'todos/index.html' },
  ];
};
