var IndexCtrl = function($scope){
	$scope.examples = [
    { name: 'Hello AngularJS', href: 'hello.html' },
    { name: 'ngInit, ngChecked, ngDisabled 及 ngReadonly', href: 'init-ect.html' },
    { name: 'Controller', href: 'controller.html' },
    { name: 'ngShow 與 ngHide', href: 'show-and-hide.html' },
    { name: 'ng-repeat (一)', href: 'repeat-1.html' },
    { name: 'ng-repeat (二)', href: 'repeat-2.html' },
    { name: 'ng-repeat (三)', href: 'repeat-3.html' },
    { name: 'ng-click 與 ng-dblclick（一）', href: 'click-dblclick-1.html' },
    { name: 'ng-click 與 ng-dblclick（二）', href: 'click-dblclick-2.html' },
    { name: 'Filters（一）', href: 'filters-1.html' },
    { name: 'Filters（二）', href: 'filters-2.html' },
    { name: 'Filters（三）', href: 'filters-3.html' },
    { name: 'Options（一）', href: 'options-1.html' },
    { name: 'Options（二）', href: 'options-2.html' },
    { name: 'Options（三）', href: 'options-3.html' },
    { name: 'ng-change', href: 'change.html' },
    { name: 'ng-href 與 ng-src', href: 'href-src.html' },
    { name: 'Module', href: 'module.html' },
    { name: 'Dependency Injection', href: 'inject.html' },
    { name: 'Route 與 ng-view', href: 'route.html' },
    { name: 'ng-if', href: 'ngif.html' },
    { name: 'ngCalss', href: 'ngcalss.html' },
    { name: 'ng-class-even 與 ng-class-odd', href: 'ngclass-even-odd.html' },
    { name: 'ng-style', href: 'style.html' },
    { name: 'ng-list', href: 'list.html' },
    { name: 'ng-focus 與 ngBlur', href: 'focus-blur.html' },
    { name: '自訂過濾器', href: 'custom-filter.html' },
    { name: '自訂表達式（模板）符號', href: 'custom-interpolation.html' },
    { name: 'ng-bind', href: 'bind.html' },
    { name: 'ng-submit', href: 'submit.html' },
  ];
};
